name: vanilla-gnome-default-settings
type: dpkg-buildpackage
source:
  type: git
  url: https://github.com/Vanilla-OS/vanilla-gnome-default-settings.git
  branch: main
  commit: latest
  paths:
  - vanilla-gnome-default-settings
modules:
- name: vanilla-gnome-default-settings-deps-install
  type: apt
  source:
    packages:
    - dpkg-dev
    - libglib2.0-bin
